In [16]:
import torch

inputs = torch.tensor([[0.4, 0.1, 0.8], [0.5, 0.8, 0.6], [0.5, 0.8, 0.6], [0, 0.8, 0.5]])

query = inputs[1]

attn_scores = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores[i] = torch.dot(x_i, query)

print(attn_scores)

tensor([0.7600, 1.2500, 1.2500, 0.9400])


In [33]:
tt = torch.tensor([1, 2, 3, 4, 5, 7]).float()
tt_tmp = tt / tt.sum()
print(f'softmax weights: {tt_tmp}')
print(f'softmax sum: {tt_tmp.sum()}')

softmax weights: tensor([0.0455, 0.0909, 0.1364, 0.1818, 0.2273, 0.3182])
softmax sum: 1.0


In [ ]:
def soft_max(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

bad_soft_max_scores = soft_max(tt)
print(f'softmax weights: {bad_soft_max_scores}')
print(f'softmax sum: {bad_soft_max_scores.sum()}')

soft_max_scores = torch.softmax(tt, dim=0)
print(f'softmax weights: {soft_max_scores}')
print(f'softmax sum: {soft_max_scores.sum()}')


softmax weights: tensor([0.0020, 0.0056, 0.0151, 0.0411, 0.1116, 0.8246])
softmax sum: 1.0
softmax weights: tensor([0.0020, 0.0056, 0.0151, 0.0411, 0.1116, 0.8246])
softmax sum: 1.0


In [ ]:
def simple_attention_weights(inputs):
    attn_weights = inputs @ inputs.T
    attn_weights = torch.softmax(attn_weights, dim=-1)

    all_context_vecs = attn_weights @ inputs
    '''context_score = torch.empty(query.shape)
    for i, x_i in enumerate(inputs):
        context_score += attn_scores[i]*x_i

    print(context_score)'''

simple_attention_weights(inputs)

tensor([[0.8100, 0.7600, 0.7600, 0.4800],
        [0.7600, 1.2500, 1.2500, 0.9400],
        [0.7600, 1.2500, 1.2500, 0.9400],
        [0.4800, 0.9400, 0.9400, 0.8900]])
tensor([[0.2761, 0.2627, 0.2627, 0.1985],
        [0.1831, 0.2989, 0.2989, 0.2192],
        [0.1831, 0.2989, 0.2989, 0.2192],
        [0.1762, 0.2791, 0.2791, 0.2655]])
